### ISSUE TITLE
Assembly to C function: Making library

### ISSUE THREAD

**Issue by techmasterz** [llamaking136/danix#3]
Looks like you used Assembly code as C function. ex:  
``` outb(arg1, arg2) /* of course hex code */  ```
I think you should library like this for OS developers, but if I would you, I would make library like I said.

If you are accept my idea, I'll make OS and I'll say it was thanks to llamaking136.

    - techmasterz, 2021

**Comment by llamaking136** [comment]
Sounds cool.
