### ISSUE TITLE
Windows Implementation

### ISSUE THREAD

**Issue by techmasterz** [llamaking136/danix#4]
I was tried implement and almost worked but gives this error:

Makefile:
   -  python Make.py kernel
   -   File not found - *.asm
   -  File not found - *.c

**Comment by techmasterz** [comment]
Also prints python's first letter as upper

**Comment by llamaking136** [comment]
Do you think you could provide a screenshot? I think the Make.py script is trying to find files using a Linux-specific command. I actually haven't tried this out on Windows.

**Comment by techmasterz** [comment]
Yeah you are right and I'll add python makefile as a Windows version. Now I'm closing issue, thank you.
