### ISSUE TITLE
I can't load from GRUB

### ISSUE THREAD

**Issue by alimkoca** [llamaking136/danix#5]
GRUB iso works but when I click to my operating system shows nothing
kernel.c code:
```
int kmain(){
    print("Hello"); // It's function in kernel.h file
}
```

**Comment by techmasterz** [comment]
In my repo your repo is excellent

**Comment by techmasterz** [comment]
So I want help

**Comment by llamaking136** [comment]
Sure, I could try and help. Which repo is it?

**Comment by techmasterz** [comment]
papatya_linux_main
