### ISSUE TITLE
Thanks for contributing to our wiki + contacts

### ISSUE THREAD

**Issue by Yukonus** [llamaking136/danix#7]
Hey! Thanks for your fast contribution to the Canine Rocket Tech wiki! I really appreciate it! I really liked your writing style and organizational skills, is there any other way I can reach out? I believe I've talked to you before in the past.

**Comment by llamaking136** [comment]
I believe you may have under a similar username. If you would like to reach out, my Discord is `llamaking#3730` and my Matrix is `@llamaking136:matrix.org`. (Hopefully the latter still works...)
Thanks for reaching out!
